spring:
  application:
    name: locadora-rdt-backend

  datasource:
    url: jdbc:h2:mem:testdb-locadora
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
